export const LOAD_TRANSACTIONS = 'LOAD_TRANSACTIONS'
export const SELECT_TRANSACTION = 'SELECT_TRANSACTION'
export const ACCOUNT_NAME = 'ACCOUNT_NAME'
export const TRANSACTION_TYPE = 'TRANSACTION_TYPE'
