export const BASE_URL = 'http://10.0.0.35:3000'

export const UPDATING_USER = 'UPDATING_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const AUTHENTICATING = 'AUTHENTICATING'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const GUEST_SUCCESS = 'GUEST_SUCCESS'

export const GUEST_FAILURE = 'GUEST_FAILURE'
export const RESET_ERROR = 'RESET_ERROR'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'

export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE'
export const GET_GUEST_TOKEN_SUCCESS = 'GET_GUEST_TOKEN_SUCCESS'
export const GET_GUEST_TOKEN_FAILURE = 'GET_GUEST_TOKEN_FAILURE'

export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNOUT_FAILURE = 'SIGNOUT_FAILURE'

export const SHOWING_USER = 'SHOWING_USER'
export const SHOW_USER_SUCCESS = 'SHOW_USER_SUCCESS'
export const SHOW_USER_FAILURE = 'SHOW_USER_FAILURE'

export const FETCHING = 'FETCHING'
export const GET_BUYER_BIDS_SUCCESS = 'GET_BUYER_BIDS_SUCCESS'
export const GET_BUYER_BIDS_FAILURE = 'GET_BUYER_BIDS_FAILURE'

export const GET_ALL_BIDS_SUCCESS = 'GET_ALL_BIDS_SUCCESS'
export const GET_ALL_BIDS_FAILURE = 'GET_ALL_BIDS_FAILURE'

export const GET_SUPPLIER_OFFERS_SUCCESS = 'GET_SUPPLIER_OFFERS_SUCCESS'
export const GET_SUPPLIER_OFFERS_FAILURE = 'GET_SUPPLIER_OFFERS_FAILURE'

export const GET_ALL_OFFERS_SUCCESS = 'GET_ALL_OFFERS_SUCCESS'
export const GET_ALL_OFFERS_FAILURE = 'GET_ALL_OFFERS_FAILURE'

export const SELECT_BID = 'SELECT_BID'
export const SELECT_OFFER = 'SELECT_OFFER'

export const CREATING_OFFER = 'CREATING_OFFER'
export const CREATE_OFFER_SUCCESS = 'CREATE_OFFER_SUCCESS'
export const CREATE_OFFER_FAILURE = 'CREATE_OFFER_FAILURE'

export const CREATING_BID = 'CREATING_BID'
export const CREATE_BID_SUCCESS = 'CREATE_BID_SUCCESS'
export const CREATE_BID_FAILURE = 'CREATE_BID_FAILURE'
