export const BASE_URL = 'http://10.0.0.35:3000'

export const UPDATING_USER = 'UPDATING_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const AUTHENTICATING = 'AUTHENTICATING'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const GUEST_SUCCESS = 'GUEST_SUCCESS'

export const GUEST_FAILURE = 'GUEST_FAILURE'
export const RESET_ERROR = 'RESET_ERROR'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'

export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE'
export const GET_GUEST_TOKEN_SUCCESS = 'GET_GUEST_TOKEN_SUCCESS'
export const GET_GUEST_TOKEN_FAILURE = 'GET_GUEST_TOKEN_FAILURE'

export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNOUT_FAILURE = 'SIGNOUT_FAILURE'

export const SHOWING_USER = 'SHOWING_USER'
export const SHOW_USER_SUCCESS = 'SHOW_USER_SUCCESS'
export const SHOW_USER_FAILURE = 'SHOW_USER_FAILURE'

export const FETCHING = 'FETCHING'
export const GET_BUYER_BIDS_SUCCESS = 'GET_BUYER_BIDS_SUCCESS'
export const GET_BUYER_BIDS_FAILURE = 'GET_BUYER_BIDS_FAILURE'

export const GET_ALL_BIDS_SUCCESS = 'GET_ALL_BIDS_SUCCESS'
export const GET_ALL_BIDS_FAILURE = 'GET_ALL_BIDS_FAILURE'

export const GET_SUPPLIER_OFFERS_SUCCESS = 'GET_SUPPLIER_OFFERS_SUCCESS'
export const GET_SUPPLIER_OFFERS_FAILURE = 'GET_SUPPLIER_OFFERS_FAILURE'

export const GET_ALL_OFFERS_SUCCESS = 'GET_ALL_OFFERS_SUCCESS'
export const GET_ALL_OFFERS_FAILURE = 'GET_ALL_OFFERS_FAILURE'

export const SELECT_BID = 'SELECT_BID'
export const SELECT_OFFER = 'SELECT_OFFER'

export const CREATING_OFFER = 'CREATING_OFFER'
export const CREATE_OFFER_SUCCESS = 'CREATE_OFFER_SUCCESS'
export const CREATE_OFFER_FAILURE = 'CREATE_OFFER_FAILURE'

export const DELETING_OFFER = 'DELETING_OFFER'
export const DELETE_OFFER_SUCCESS = 'DELETE_OFFER_SUCCESS'
export const DELETE_OFFER_FAILURE = 'DELETE_OFFER_FAILURE'

export const DELETING_BID = 'DELETING_BID'
export const DELETE_BID_SUCCESS = 'DELETE_BID_SUCCESS'
export const DELETE_BID_FAILURE = 'DELETE_BID_FAILURE'

export const CREATING_BID = 'CREATING_BID'
export const CREATE_BID_SUCCESS = 'CREATE_BID_SUCCESS'
export const CREATE_BID_FAILURE = 'CREATE_BID_FAILURE'
export const CLAIM_BID = "CLAIM_BID"
export const CLAIM_OFFER = "CLAIM_OFFER"

export const FETCH_PRODUCTS_SUCCESS="FETCH_PRODUCTS_SUCCESS"
export const FETCH_PRODUCTS_FAILURE="FETCH_PRODUCTS_FAILURE"
export const CLEARING_ALL_PRODUCTS="CLEARING_ALL_PRODUCTS"
export const CLEAR_ALL_PRODUCTS_SUCCESS="CLEAR_ALL_PRODUCTS_SUCCESS"
export const CLEAR_ALL_PRODUCTS_FAILURE="CLEAR_ALL_PRODUCTS_FAILURE"
export const SELECT_PRODUCT="SELECT_PRODUCT"

export const CREATING_PRODUCT="CREATING_PRODUCT"
export const CREATE_PRODUCT_SUCCESS="CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAILURE="CREATE_PRODUCT_FAILURE"
export const UPDATING_PRODUCT="UPDATING_PRODUCT"
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAILURE="UPDATE_PRODUCT_FAILURE"
export const DELETING_PRODUCT="DELETING_PRODUCT"
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILURE="DELETE_PRODUCT_FAILURE"

export const FETCH_BID_SUCCESS="FETCH_BID_SUCCESS"
export const FETCH_BID_FAILURE="FETCH_BID_FAILURE"
export const FETCH_OFFER_SUCCESS="FETCH_OFFER_SUCCESS"
export const FETCH_OFFER_FAILURE="FETCH_OFFER_FAILURE"
export const FETCH_ORDERS_SUCCESS="FETCH_ORDERS_SUCCESS"
export const FETCH_ORDERS_FAILURE ="FETCH_ORDERS_FAILURE"
export const CLEARING_ALL_ORDERS="CLEARING_ALL_ORDERS"
export const CLEAR_ALL_ORDERS_SUCCESS="CLEAR_ALL_ORDERS_SUCCESS"
export const CLEAR_ALL_ORDERS_FAILURE="CLEAR_ALL_ORDERS_FAILURE"
export const SELECT_ORDER="SELECT_ORDER"
export const CREATING_ORDER="CREATING_ORDER"
export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAILURE="CREATE_ORDER_FAILURE"
export const UPDATING_ORDER="UPDATING_ORDER"
export const UPDATE_ORDER_SUCCESS="UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_FAILURE="UPDATE_ORDER_FAILURE"
export const DELETING_ORDER="DELETING_ORDER"
export const DELETE_ORDER_SUCCESS="DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_FAILURE="DELETE_ORDER_FAILURE"
