export const BASE_URL = 'http://107.77.223.35:3000'

export const UPDATING_USER = 'UPDATING_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const AUTHENTICATING = 'AUTHENTICATING'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const GUEST_SUCCESS = 'GUEST_SUCCESS'

export const GUEST_FAILURE = 'GUEST_FAILURE'
export const RESET_ERROR = 'RESET_ERROR'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'

export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE'
export const GET_GUEST_TOKEN_SUCCESS = 'GET_GUEST_TOKEN_SUCCESS'
export const GET_GUEST_TOKEN_FAILURE = 'GET_GUEST_TOKEN_FAILURE'

export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNOUT_FAILURE = 'SIGNOUT_FAILURE'

export const SHOWING_USER = 'SHOWING_USER'
export const SHOW_USER_SUCCESS = 'SHOW_USER_SUCCESS'
export const SHOW_USER_FAILURE = 'SHOW_USER_FAILURE'
